# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Get Listings

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  get-prices:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
    - run: npm ci
    - run: node index.js
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update Listings
      
